name: CI Pipeline
on:
  workflow_dispatch: 

env:
  GLOBAL_APP_ENV: global-dev

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JOB_APP_ENV: job-dev

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven' 

      - name: Say Hello
        run: echo "Hello, World!"

      - name: Install
        env:
          APP_DEMO: demo
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: echo "Environment $APP_DEMO"

      - name: Run Spring Boot Tests
        working-directory: ./service-a 
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }} 
        run: ./mvnw test 